FROM python:3

WORKDIR /usr/src/app

ARG CONSUMER_KEY
ARG CONSUMER_SECRET
ARG ACCESS_TOKEN
ARG ACCESS_TOKEN_SECRET
ARG SUB_TOKEN
ARG GEOP_HOST

ENV CONSUMER_KEY=$CONSUMER_KEY
ENV CONSUMER_SECRET=$CONSUMER_SECRET
ENV ACCESS_TOKEN=$ACCESS_TOKEN
ENV ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
ENV SUB_TOKEN=$SUB_TOKEN
ENV GEOP_HOST=$GEOP_HOST

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "-u" ,"./main.py" ]
